### ISSUE TITLE
There is bug in the Safari browser below the Mac system.

### ISSUE THREAD

**Issue by leihg** [anein/angular2-trim-directive#23] opened 2018-08-31 01:47 UTC
When used under the Safari browser on the MAC system, there is a bug in the input. Each keystroke will copy the characters entered earlier. The official demo also has this problem. Hope to fix it.

**Comment by anein** [comment] 2018-10-20 20:11
Duplicate of #13

**Comment by anein** [comment] 2019-12-09 11:50
Fixed #36

**Closed by anein** 2019-12-09 11:50 UTC
